spring:
  jms:
    cache:
      enabled: true
      connection-cache-size: 1      # Single connection
      session-cache-size: 3
    pool:
      enabled: true
      max-connections: 1            # Only one connection
      max-sessions-per-connection: 3
    ibm:
      mq:
        automatic-reconnect: true
        reconnect-delay: 60000      # Wait 60 seconds between reconnects
