spring:
  jms:
    cache:
      enabled: true
      connection-cache-size: 5
      session-cache-size: 10
      cache-consumers: true
    # Critical for MQRC 2538
    ibm:
      mq:
        queue-manager: YOUR_QMGR
        channel: YOUR_CHANNEL
        conn-name: hostname(1414)
        # Automatic reconnection settings
        automatic-reconnect: true
        reconnect-delay: 5000              # 5 seconds between attempts
        client-reconnect-timeout: 1800     # 30 minutes total
        reconnect-retry-count: 999999      # Essentially unlimited
        # Connection timeout settings
        connection-timeout: 30000          # 30 seconds
        read-timeout: 30000                # 30 seconds
        receive-timeout: 30000             # 30 seconds for polling
        # Heartbeat settings (if supported)
        heartbeat-interval: 300            # 5 minutes
        keep-alive-interval: 60            # 1 minute
