# application.yaml
management:
  health:
    jms:
      enabled: false  # Disable JMS health check temporarily
    # OR configure it properly
    jms:
      enabled: true
      timeout: 10s    # Increase timeout
    
endpoints:
  health:
    sensitive: false

# Alternative: Disable all JMS auto-configuration if needed
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
