apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: jms-current-gen
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    metadata:
      labels:
        workload: jms-critical
        instance-generation: "current"
    spec:
      requirements:
        # On-Demand instances only
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        
        # Current generation instances (5th, 6th, 7th gen)
        - key: "karpenter.k8s.aws/instance-generation"
          operator: In
          values: ["5", "6", "7"]
        
        # Specific instance families for JMS
        - key: "node.kubernetes.io/instance-family"
          operator: In
          values: ["m5", "m6i", "m7i", "m6a", "m6in"]
        
        # Spread across 3 AZs
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-west-2a", "us-west-2b", "us-west-2c"]
        
        # x86 architecture
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
      
      # Limits to ensure 2 nodes per AZ (6 total)
      limits:
        resources:
          cpu: 48  # Limits total CPU across all nodes
          memory: 192Gi
  
      kubelet:
        maxPods: 110
        systemReserved:
          cpu: 100m
          memory: 512Mi
        kubeReserved:
          cpu: 100m
          memory: 512Mi
