apiVersion: v1
kind: Pod
metadata:
  name: network-tools-pod
spec:
  containers:
  - name: tools
    image: alpine:latest
    command: ["/bin/sh"]
    args: 
    - "-c"
    - |
      apk update
      apk add busybox-extras curl wget netcat-openbsd
      sleep infinity
