apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-service
spec:
  replicas: 6
  template:
    spec:
      topologySpreadConstraints:
      # First priority: Spread across AZs
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: jms-service
      # Second priority: Spread across nodes within AZ
      - maxSkew: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: jms-service
